create table if not exists public.construction_items (
    id bigint generated by default as identity primary key,
    block_id integer not null,
    name text not null,
    material text default '',
    planned numeric default 0,
    used numeric default 0,
    unit text default 'm3',
    price numeric default 0,
    updated_at timestamptz default now()
);

alter table public.construction_items enable row level security;

drop policy if exists "read construction" on public.construction_items;
drop policy if exists "insert construction" on public.construction_items;
drop policy if exists "update construction" on public.construction_items;

create policy "read construction"
on public.construction_items
for select
to anon, authenticated
using (true);

create policy "insert construction"
on public.construction_items
for insert
to anon, authenticated
with check (true);

create policy "update construction"
on public.construction_items
for update
to anon, authenticated
using (true)
with check (true);

alter publication supabase_realtime
add table public.construction_items;